site_name: CSAF
site_description: Yes, another such thing.

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sthagen/csaf
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/shagen/csaf
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2021 Stefan Hagen under the MIT license

repo_name: sthagen/csaf
repo_url: https://github.com/sthagen/csaf
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: 'index.md'
  - Quickstart: 'quick.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - API: 'api.md'
  - CLI: 'cli.md'
  - Background: 'background.md'
  - Changes: 'changes.md'
  - Test Coverage: https://codes.dilettant.life/coverage/csaf
  - Third-Party: 'third-party/README.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:

