[tool.pyflow]
name = "casf"
py_version = "3.8"
# [[[fill version_sync()]]]
version = "2022.3.14"
# [[[end]]] (checksum: 3239a27d9a4b91f89023d7d20de106cd)
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
